builds:
  - builder: prebuilt
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    goamd64:
      - v1
    prebuilt:
      path: "{{ .Os }}/testkube_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/kubectl-testkube{{ .Ext }}"
    binary: kubectl-testkube
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source 
    artifacts: source

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes"
    artifacts: all
    output: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  # Create a thread in the General category in the repo's discussion tab.
  discussion_category_name: General

  # Tags that have the format v1.0.0-rc1 will mark the release as a pre-release (i.e. not ready for production)
  # Other tags will be marked as ready for production
  prerelease: auto

brews:
  - tap:
      owner: kubeshop
      name: homebrew-testkube-dev
    description: Testkube - your somewhat opinionated and friendly Kubernetes testing framework!
    homepage: https://testkube.io
    license: "MIT"
    dependencies:
      - name: helm
      - name: kubectl
    install: |
      bin.install "kubectl-testkube"
      ln_s bin/"kubectl-testkube", bin/"tk"
      ln_s bin/"kubectl-testkube", bin/"testkube"

nfpms:
  - maintainer: Testkube team
    license: "MIT"
    formats:
      - deb

dockers:
  - dockerfile: ./build/kubectl-testkube/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-cli:{{ .Version }}-{{ .Arch }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
      - "--build-arg=ALPINE_IMAGE={{ .Env.ALPINE_IMAGE }}"

  - dockerfile: ./build/kubectl-testkube/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-cli:{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
      - "--build-arg=ALPINE_IMAGE={{ .Env.ALPINE_IMAGE }}"

docker_manifests:
  - name_template: kubeshop/testkube-cli:{{ .Version }}
    image_templates:
      - kubeshop/testkube-cli:{{ .Version }}-amd64
      - kubeshop/testkube-cli:{{ .Version }}-arm64v8
  - name_template: kubeshop/testkube-cli:latest
    image_templates:
      - kubeshop/testkube-cli:{{ .Version }}-amd64
      - kubeshop/testkube-cli:{{ .Version }}-arm64v8
