builds:
  - id: "linux"
    main: "./contrib/executor/jmeter/cmd/agent"
    binary: "jmeter"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/jmeter/build/agent/Dockerfile"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-jmeter-executor:{{ .ShortCommit }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
    extra_files:
    - ./contrib/executor/jmeter/lib/jmeter-plugins-cmn-jmeter-0.6.jar
    - ./contrib/executor/jmeter/plugins/jmeter-plugins-functions-2.1.jar
    - ./contrib/executor/jmeter/plugins/jmeter-plugins-manager-1.3.jar
    - ./contrib/executor/jmeter/scripts/entrypoint.sh

release:
  disable: true

snapshot:
  name_template: '{{ .ShortCommit }}'