builds:
  - id: "linux"
    main: "./contrib/executor/gradle/cmd/agent"
    binary: "gradle"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk8"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk8-amd64"
      - "kubeshop/testkube-gradle-executor:jdk8-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk8"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk8-arm64v8"
      - "kubeshop/testkube-gradle-executor:jdk8-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk11"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk11-amd64"
      - "kubeshop/testkube-gradle-executor:jdk11-amd64"
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-amd64"
      - "kubeshop/testkube-gradle-executor:latest-amd64"
      - "kubeshop/testkube-gradle-executor:{{ .ShortCommit }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk11"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk11-arm64v8"
      - "kubeshop/testkube-gradle-executor:jdk11-arm64v8"
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-arm64v8"
      - "kubeshop/testkube-gradle-executor:latest-arm64v8"
      - "kubeshop/testkube-gradle-executor:{{ .ShortCommit }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk17"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-amd64"
      - "kubeshop/testkube-gradle-executor:jdk17-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk17"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-arm64v8"
      - "kubeshop/testkube-gradle-executor:jdk17-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk18"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-amd64"
      - "kubeshop/testkube-gradle-executor:jdk18-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk18"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-arm64v8"
      - "kubeshop/testkube-gradle-executor:jdk18-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}-jdk8
    image_templates:
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk8-amd64
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk8-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:jdk8
    image_templates:
      - kubeshop/testkube-gradle-executor:jdk8-amd64
      - kubeshop/testkube-gradle-executor:jdk8-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}-jdk11
    image_templates:
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk11-amd64
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk11-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:jdk11
    image_templates:
      - kubeshop/testkube-gradle-executor:jdk11-amd64
      - kubeshop/testkube-gradle-executor:jdk11-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17
    image_templates:
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-amd64
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:jdk17
    image_templates:
      - kubeshop/testkube-gradle-executor:jdk17-amd64
      - kubeshop/testkube-gradle-executor:jdk17-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18
    image_templates:
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-amd64
      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:jdk18
    image_templates:
      - kubeshop/testkube-gradle-executor:jdk18-amd64
      - kubeshop/testkube-gradle-executor:jdk18-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:latest
    image_templates:
      - kubeshop/testkube-gradle-executor:latest-amd64
      - kubeshop/testkube-gradle-executor:latest-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}
    image_templates:
      - kubeshop/testkube-gradle-executor:{{ .Version }}-amd64
      - kubeshop/testkube-gradle-executor:{{ .Version }}-arm64v8
  - name_template: kubeshop/testkube-gradle-executor:{{ .ShortCommit }}
    image_templates:
      - kubeshop/testkube-gradle-executor:{{ .ShortCommit }}-amd64
      - kubeshop/testkube-gradle-executor:{{ .ShortCommit }}-arm64v8

release:
  disable: true