env:
  # Goreleaser always uses the docker buildx builder with name "default"; see
  # https://github.com/goreleaser/goreleaser/pull/3199
  # To use a builder other than "default", set this variable.
  # Necessary for, e.g., GitHub actions cache integration.
  - DOCKER_BUILDX_BUILDER={{ if index .Env "DOCKER_BUILDX_BUILDER"  }}{{ .Env.DOCKER_BUILDX_BUILDER }}{{ else }}default{{ end }}
  # Setup to enable Docker to use, e.g., the GitHub actions cache; see
  # https://docs.docker.com/build/building/cache/backends/
  # https://github.com/moby/buildkit#export-cache
  - DOCKER_BUILDX_CACHE_FROM={{ if index .Env "DOCKER_BUILDX_CACHE_FROM"  }}{{ .Env.DOCKER_BUILDX_CACHE_FROM }}{{ else }}type=registry{{ end }}
  - DOCKER_BUILDX_CACHE_TO={{ if index .Env "DOCKER_BUILDX_CACHE_TO"  }}{{ .Env.DOCKER_BUILDX_CACHE_TO }}{{ else }}type=inline{{ end }}

builds:
  - id: "linux"
    main: "./contrib/executor/{{ .Env.EXECUTOR }}/cmd/agent"
    binary: "{{ .Env.EXECUTOR }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.{{ .Env.EXECUTOR_VERSION }}"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-amd64"
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Env.EXECUTOR_VERSION }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.{{ .Env.EXECUTOR_VERSION }}"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-arm64v8"
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Env.EXECUTOR_VERSION }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk11"
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-amd64"
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.created={{ .Date}}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk11"
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-arm64v8"
      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

#  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk17"
#    use: buildx
#    goos: linux
#    goarch: amd64
#    image_templates:
#      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-jdk17-amd64"
#      - "kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:jdk17-amd64"
#    build_flag_templates:
#      - "--platform=linux/amd64"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.created={{ .Date}}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
#      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
#      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
#
#  - dockerfile: "./contrib/executor/{{ .Env.EXECUTOR }}/build/agent/Dockerfile.jdk17"
#    use: buildx
#    goos: linux
#    goarch: arm64
#    image_templates:
#      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-arm64v8"
#      - "kubeshop/testkube-gradle-executor:jdk17-arm64v8"
#    build_flag_templates:
#      - "--platform=linux/arm64/v8"
#      - "--label=org.opencontainers.image.created={{ .Date }}"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
#      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
#      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
#
#  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk18"
#    use: buildx
#    goos: linux
#    goarch: amd64
#    image_templates:
#      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-amd64"
#      - "kubeshop/testkube-gradle-executor:jdk18-amd64"
#    build_flag_templates:
#      - "--platform=linux/amd64"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.created={{ .Date}}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
#      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
#      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"
#
#  - dockerfile: "./contrib/executor/gradle/build/agent/Dockerfile.jdk18"
#    use: buildx
#    goos: linux
#    goarch: arm64
#    image_templates:
#      - "kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-arm64v8"
#      - "kubeshop/testkube-gradle-executor:jdk18-arm64v8"
#    build_flag_templates:
#      - "--platform=linux/arm64/v8"
#      - "--label=org.opencontainers.image.created={{ .Date }}"
#      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
#      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
#      - "--builder={{ .Env.DOCKER_BUILDX_BUILDER }}"
#      - "--cache-to={{ .Env.DOCKER_BUILDX_CACHE_TO }}"
#      - "--cache-from={{ .Env.DOCKER_BUILDX_CACHE_FROM }}"

docker_manifests:
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-{{ .Env.EXECUTOR_VERSION }}-arm64v8
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Env.EXECUTOR_VERSION }}
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Env.EXECUTOR_VERSION }}-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Env.EXECUTOR_VERSION }}-arm64v8
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-jdk11
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-jdk11-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-jdk11-arm64v8
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:jdk11
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:jdk11-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:jdk11-arm64v8
#  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17
#    image_templates:
#      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-amd64
#      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk17-arm64v8
#  - name_template: kubeshop/testkube-gradle-executor:jdk17
#    image_templates:
#      - kubeshop/testkube-gradle-executor:jdk17-amd64
#      - kubeshop/testkube-gradle-executor:jdk17-arm64v8
#  - name_template: kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18
#    image_templates:
#      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-amd64
#      - kubeshop/testkube-gradle-executor:{{ .Version }}-jdk18-arm64v8
#  - name_template: kubeshop/testkube-gradle-executor:jdk18
#    image_templates:
#      - kubeshop/testkube-gradle-executor:jdk18-amd64
#      - kubeshop/testkube-gradle-executor:jdk18-arm64v8
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:latest
    image_templates:
      - kubeshop/testkube-gradle-{{ .Env.EXECUTOR }}:latest-amd64
      - kubeshop/testkube-gradle-{{ .Env.EXECUTOR }}:latest-arm64v8
  - name_template: kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}
    image_templates:
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-amd64
      - kubeshop/testkube-{{ .Env.EXECUTOR }}-executor:{{ .Version }}-arm64v8


release:
  disable: true