name: Docker images build with GoReleaser
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]-beta-*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: getting Tag name pushed.
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release -f goreleaser_files/.goreleaser-docker-build-api.yml
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          VERSION: ${{ steps.vars.outputs.tag }}
          COMMIT: ${{ github.sha }}
          ANALYTICS_TRACKING_ID: ${{secrets.TESTKUBE_API_GA_MEASUREMENT_ID}}
          ANALYTICS_API_KEY: ${{secrets.TESTKUBE_API_GA_MEASUREMENT_SECRET}}
          SLACK_BOT_CLIENT_ID: ${{secrets.TESTKUBE_SLACK_BOT_CLIENT_ID}}
          SLACK_BOT_CLIENT_SECRET: ${{secrets.TESTKUBE_SLACK_BOT_CLIENT_SECRET}}
          SEGMENTIO_KEY: ${{secrets.TESTKUBE_API_SEGMENTIO_KEY}}
          CLOUD_SEGMENTIO_KEY: ${{secrets.TESTKUBE_API_CLOUD_SEGMENTIO_KEY}}

#      - name: Editing helm-release repo with version based on a Tag pushed.
#        run: |
#
#          # Setting up Git:
#
#          git clone https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts
#          cd ./helm-charts
#          git config user.name "kubeshop-bot"
#          git config user.email "kubeshop-bot@kubeshop.io"
#          git checkout -b "release-$RELEASE_VERSION"
#
#          # Calling chart releaser script by passing needed folder name:
#          # E.G. in order to relase testkube-api":
#          # -->> ./chart_releaser.sh --helm-chart-folder testkube-api
#
#          export GH_PUSH_TOKEN
#          export RELEASE_VERSION
#
#          cd ./scripts
#          ./chart_releaser.sh --helm-chart-folder testkube-api --main-chart true --branch true
#
#        env:
#          GH_PUSH_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
#          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
#
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          event-type: trigger-executor-docker-build
#          client-payload: '{"release_version": "${{ steps.vars.outputs.tag }}"}'
