name: release
on:
  push:
#    tags:
#      - "v[0-9]+.[0-9]+.[0-9]+-*"
    branches:
      - main
permissions:
  contents: read
jobs:
  release_api:
    needs: create_branch
    uses: "kubeshop/testkube/.github/workflows/docker-build-tag.yaml@main"

  create_branch:
    runs-on: ubuntu-latest
    needs: create_branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Editing helm-release repo with version based on a Tag pushed.
        run: |
          # Setting up Git:

          git clone https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts
          cd ./helm-charts
          git config user.name "kubeshop-bot"
          git config user.email "kubeshop-bot@kubeshop.io"
          git checkout -b "release-$RELEASE_VERSION"

          # Calling chart releaser script by passing needed folder name:
          # E.G. in order to relase testkube-api":
          # -->> ./chart_releaser.sh --helm-chart-folder testkube-api

          export GH_PUSH_TOKEN
          export RELEASE_VERSION
          cd ./scripts
          ./chart_releaser.sh --helm-chart-folder testkube-api --main-chart true --branch true
        env:
          GH_PUSH_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}


  release_executors:
    needs: release_api
    uses: "kubeshop/testkube/.github/workflows/executor_docker-build.yaml@main"

  releasing_helm_chart_executor:
    needs: release_executors
    runs-on: ubuntu-latest
    steps:
      - name: Editing helm-release repo with version based on a Tag pushed.
        run: |

          # Setting up Git:

          git clone https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts
          cd ./helm-charts
          git config user.name "kubeshop-bot"
          git config user.email "kubeshop-bot@kubeshop.io"

          git fetch origin "release-$RELEASE_VERSION"
          git checkout "release-$RELEASE_VERSION"

          # Calling chart releaser script by passing needed folder name:
          # E.G. in order to relase api-server":
          # -->> ./chart_releaser.sh --helm-chart-folder api-server

          export GH_PUSH_TOKEN
          export RELEASE_VERSION

          cd ./scripts
          executors="artillery curl cypress ginkgo gradle init jmeter k6 kubepug maven playwright postman scraper soapui"
          for executor in $executors
          do
            ./chart_releaser.sh --testkube-executor-name ${executor} --main-chart false --branch true
          done

          git checkout main
          git merge "release-$RELEASE_VERSION"
          # git push origin main
          git push --set-upstream https://kubeshop-bot:$GH_PUSH_TOKEN@github.com/kubeshop/helm-charts main
        env:
          GH_PUSH_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          RELEASE_VERSION: ${{ github.event.client_payload.release_version }}


